/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.BodyDeclaration;
import javaMM.Comment;
import javaMM.TypeAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.AbstractTypeDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractTypeDeclarationValidator {
	boolean validate();

	boolean validateBodyDeclarations(EList<BodyDeclaration> value);
	boolean validateCommentsBeforeBody(EList<Comment> value);
	boolean validateCommentsAfterBody(EList<Comment> value);
	boolean validatePackage(javaMM.Package value);
	boolean validateSuperInterfaces(EList<TypeAccess> value);
}
