/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.AnnotationTypeMemberDeclaration;
import javaMM.Expression;

/**
 * A sample validator interface for {@link javaMM.AnnotationMemberValuePair}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationMemberValuePairValidator {
	boolean validate();

	boolean validateMember(AnnotationTypeMemberDeclaration value);
	boolean validateValue(Expression value);
}
