/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.ArrayInitializer;
import javaMM.Expression;
import javaMM.TypeAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.ArrayCreation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArrayCreationValidator {
	boolean validate();

	boolean validateDimensions(EList<Expression> value);
	boolean validateInitializer(ArrayInitializer value);
	boolean validateType(TypeAccess value);
}
