/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.AssignmentKind;
import javaMM.Expression;

/**
 * A sample validator interface for {@link javaMM.Assignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssignmentValidator {
	boolean validate();

	boolean validateLeftHandSide(Expression value);
	boolean validateOperator(AssignmentKind value);
	boolean validateRightHandSide(Expression value);
}
