/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Expression;
import javaMM.TypeAccess;

/**
 * A sample validator interface for {@link javaMM.CastExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CastExpressionValidator {
	boolean validate();

	boolean validateExpression(Expression value);
	boolean validateType(TypeAccess value);
}
