/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Block;
import javaMM.SingleVariableDeclaration;

/**
 * A sample validator interface for {@link javaMM.CatchClause}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CatchClauseValidator {
	boolean validate();

	boolean validateException(SingleVariableDeclaration value);
	boolean validateBody(Block value);
}
