/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Expression;
import javaMM.SingleVariableDeclaration;
import javaMM.Statement;

/**
 * A sample validator interface for {@link javaMM.EnhancedForStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnhancedForStatementValidator {
	boolean validate();

	boolean validateBody(Statement value);
	boolean validateExpression(Expression value);
	boolean validateParameter(SingleVariableDeclaration value);
}
