/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.NamedElement;

/**
 * A sample validator interface for {@link javaMM.ImportDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportDeclarationValidator {
	boolean validate();

	boolean validateStatic(boolean value);
	boolean validateImportedElement(NamedElement value);
}
