/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.BreakStatement;
import javaMM.ContinueStatement;
import javaMM.Statement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.LabeledStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LabeledStatementValidator {
	boolean validate();

	boolean validateBody(Statement value);
	boolean validateUsagesInBreakStatements(EList<BreakStatement> value);
	boolean validateUsagesInContinueStatements(EList<ContinueStatement> value);
}
