/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.AbstractMethodDeclaration;
import javaMM.MethodRefParameter;
import javaMM.TypeAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.MethodRef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodRefValidator {
	boolean validate();

	boolean validateMethod(AbstractMethodDeclaration value);
	boolean validateQualifier(TypeAccess value);
	boolean validateParameters(EList<MethodRefParameter> value);
}
