/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.MethodDeclaration;
import javaMM.TypeAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.MethodDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodDeclarationValidator {
	boolean validate();

	boolean validateExtraArrayDimensions(int value);
	boolean validateReturnType(TypeAccess value);
	boolean validateRedefinedMethodDeclaration(MethodDeclaration value);
	boolean validateRedefinitions(EList<MethodDeclaration> value);
}
