/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Archive;
import javaMM.ClassFile;
import javaMM.CompilationUnit;
import javaMM.Type;
import javaMM.UnresolvedItem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateOwnedElements(EList<javaMM.Package> value);
	boolean validateOrphanTypes(EList<Type> value);
	boolean validateUnresolvedItems(EList<UnresolvedItem> value);
	boolean validateCompilationUnits(EList<CompilationUnit> value);
	boolean validateClassFiles(EList<ClassFile> value);
	boolean validateArchives(EList<Archive> value);
}
