/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.BodyDeclaration;
import javaMM.InheritanceKind;
import javaMM.SingleVariableDeclaration;
import javaMM.VariableDeclarationExpression;
import javaMM.VariableDeclarationStatement;
import javaMM.VisibilityKind;

/**
 * A sample validator interface for {@link javaMM.Modifier}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModifierValidator {
	boolean validate();

	boolean validateVisibility(VisibilityKind value);
	boolean validateInheritance(InheritanceKind value);
	boolean validateStatic(boolean value);
	boolean validateTransient(boolean value);
	boolean validateVolatile(boolean value);
	boolean validateNative(boolean value);
	boolean validateStrictfp(boolean value);
	boolean validateSynchronized(boolean value);
	boolean validateBodyDeclaration(BodyDeclaration value);
	boolean validateSingleVariableDeclaration(SingleVariableDeclaration value);
	boolean validateVariableDeclarationStatement(VariableDeclarationStatement value);
	boolean validateVariableDeclarationExpression(VariableDeclarationExpression value);
}
