/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.PackageAccess;

/**
 * A sample validator interface for {@link javaMM.PackageAccess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageAccessValidator {
	boolean validate();

	boolean validatePackage(javaMM.Package value);
	boolean validateQualifier(PackageAccess value);
}
