/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.AbstractTypeDeclaration;
import javaMM.Model;
import javaMM.PackageAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateOwnedElements(EList<AbstractTypeDeclaration> value);
	boolean validateModel(Model value);
	boolean validateOwnedPackages(EList<javaMM.Package> value);
	boolean validatePackage(javaMM.Package value);
	boolean validateUsagesInPackageAccess(EList<PackageAccess> value);
}
