/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Expression;
import javaMM.VariableDeclaration;

/**
 * A sample validator interface for {@link javaMM.SingleVariableAccess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SingleVariableAccessValidator {
	boolean validate();

	boolean validateVariable(VariableDeclaration value);
	boolean validateQualifier(Expression value);
}
