/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.ASTNode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.TagElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TagElementValidator {
	boolean validate();

	boolean validateTagName(String value);
	boolean validateFragments(EList<ASTNode> value);
}
