/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Block;
import javaMM.CatchClause;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.TryStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TryStatementValidator {
	boolean validate();

	boolean validateBody(Block value);
	boolean validateFinally(Block value);
	boolean validateCatchClauses(EList<CatchClause> value);
}
