/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.ASTNode;
import javaMM.UnresolvedItem;

/**
 * A sample validator interface for {@link javaMM.UnresolvedItemAccess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnresolvedItemAccessValidator {
	boolean validate();

	boolean validateElement(UnresolvedItem value);
	boolean validateQualifier(ASTNode value);
}
