/**
 *
 * $Id$
 */
package javaMM.validation;

import javaMM.Expression;
import javaMM.SingleVariableAccess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link javaMM.VariableDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableDeclarationValidator {
	boolean validate();

	boolean validateExtraArrayDimensions(int value);
	boolean validateInitializer(Expression value);
	boolean validateUsageInVariableAccess(EList<SingleVariableAccess> value);
}
